#if VISTA
using System.Collections.Generic;
using UnityEngine;
using Pinwheel.Vista.Diagnostics;
using Pinwheel.Vista.Graphics;

namespace Pinwheel.Vista.BigWorld
{
    /// <summary>
    /// Blends compute-buffer biome outputs into one composite <see cref="BiomeData"/> instance.
    /// </summary>
    /// <remarks>
    /// This class handles tree buffers, detail-instance buffers, object buffers, and generic position buffers.
    /// Tree, detail-instance, and object channels store <see cref="InstanceSample"/> values. Generic buffers store
    /// <see cref="PositionSample"/> values.
    /// </remarks>
    /// <remarks>
    /// Buffer blending is mask-based instead of numerically interpolated. Each source buffer is cloned, then samples are
    /// stochastically marked invalid using the final coverage mask for that biome layer. This keeps scatter transitions
    /// spatially stable at biome boundaries while preserving the original sample layout for downstream populators.
    /// </remarks>
    /// <remarks>
    /// Call <see cref="Begin"/> once before invoking blend methods, pass the returned <see cref="BufferBlendContext"/>
    /// into every buffer blend call, then call <see cref="End"/> once to release the loaded compute shader.
    /// </remarks>
    internal static class BiomeBufferBlend
    {
        private static readonly string SHADER_NAME = "Vista/Shaders/BiomeBufferBlend";
        private static readonly int SRC_BUFFER = Shader.PropertyToID("_SrcBuffer");
        private static readonly int MASK_MAP = Shader.PropertyToID("_MaskMap");
        private static readonly int BASE_INDEX = Shader.PropertyToID("_BaseIndex");

        private static readonly string KW_DATA_TYPE_INSTANCE_SAMPLE = "DATA_TYPE_INSTANCE_SAMPLE";
        private static readonly string KW_DATA_TYPE_POSITION_SAMPLE = "DATA_TYPE_POSITION_SAMPLE";
        private static readonly string KW_FLIP_MASK = "FLIP_MASK";

        private static readonly string MAIN_KERNEL_NAME = "Main";
        private static readonly int THREAD_PER_GROUP = 8;
        /// <summary>
        /// Maximum number of thread groups sent in one dispatch. Larger buffers are processed in batches.
        /// </summary>
        private static readonly int MAX_THREAD_GROUP = 64000 / THREAD_PER_GROUP;

        /// <summary>
        /// Stores resources shared by all buffer blend calls in one biome blend pass.
        /// </summary>
        /// <remarks>
        /// Create this context with <see cref="Begin"/> and release it with <see cref="End"/>. The context keeps the
        /// compute shader loaded and caches the kernel index so each channel can dispatch without repeated lookups.
        /// </remarks>
        internal struct BufferBlendContext
        {
            /// <summary>
            /// Compute shader used to apply coverage masks to packed sample buffers.
            /// </summary>
            internal ComputeShader shader;
            /// <summary>
            /// Main kernel index resolved from <see cref="MAIN_KERNEL_NAME"/>.
            /// </summary>
            internal int kernel;
        }

        /// <summary>
        /// Creates a buffer blend context for one multi-biome blend pass.
        /// </summary>
        /// <returns>
        /// A context containing the loaded compute shader and resolved kernel index.
        /// </returns>
        /// <remarks>
        /// The returned context owns a loaded shader asset. Call <see cref="End"/> after all buffer channels have been
        /// blended.
        /// </remarks>
        internal static BufferBlendContext Begin()
        {
            ComputeShader shader = Resources.Load<ComputeShader>(SHADER_NAME);
            int kernel = shader.FindKernel(MAIN_KERNEL_NAME);
            return new BufferBlendContext { shader = shader, kernel = kernel };
        }

        /// <summary>
        /// Releases the compute shader held by a buffer blend context.
        /// </summary>
        /// <param name="ctx">Context previously created by <see cref="Begin"/>.</param>
        internal static void End(BufferBlendContext ctx)
        {
            Resources.UnloadAsset(ctx.shader);
        }

        /// <summary>
        /// Blends tree instance buffers from all source biomes into <paramref name="destData"/>.
        /// </summary>
        /// <param name="destData">Destination biome data receiving blended tree templates and buffers.</param>
        /// <param name="srcBiomes">Ordered biome list that provides blend options and transform context.</param>
        /// <param name="srcDatas">Biome output data parallel to <paramref name="srcBiomes"/>.</param>
        /// <param name="textureBlendContext">Texture blend context containing height-win masks generated by the height pass.</param>
        /// <param name="ctx">Buffer blend context created by <see cref="Begin"/>.</param>
        /// <remarks>
        /// Output entries are intentionally non-distinct. Duplicate tree templates are preserved so terrain backends can
        /// merge or interpret them according to their own population path. If no biome contributes tree buffers, this
        /// method leaves the tree channel unset in <paramref name="destData"/>.
        /// </remarks>
        internal static void BlendTreeBuffer(
            BiomeData destData, List<IBiome> srcBiomes, List<BiomeData> srcDatas, BiomeTextureBlend.BlendContext textureBlendContext, BufferBlendContext ctx)
        {
            BlendBufferChannel<TreeTemplate, InstanceSample>(
                destData,
                srcBiomes,
                srcDatas,
                textureBlendContext,
                ctx,
                (data, entries, buffers) => data.GetTrees(entries, buffers),
                (data, entry, buffer) => data.AddTree(entry, buffer),
                "Tree");

            if (VistaDebugger.isRecording)
            {
                List<TreeTemplate> finalTemplates = new();
                List<ComputeBuffer> finalBuffers = new();
                destData.GetTrees(finalTemplates, finalBuffers);
                for (int i = 0; i < finalBuffers.Count; ++i)
                {
                    string templateName = finalTemplates[i] != null ? finalTemplates[i].name : "Unnamed Template";
                    VistaDebugger.OpenScope($"Tree: {templateName}", DebugScopeType.BlendPass);
                    VistaDebugger.Capture("Final", finalBuffers[i], DebugBufferInterpretation.InstanceSample);
                    VistaDebugger.CloseScope();
                }
            }
        }

        /// <summary>
        /// Blends detail-instance buffers from all source biomes into <paramref name="destData"/>.
        /// </summary>
        /// <param name="destData">Destination biome data receiving blended detail templates and instance buffers.</param>
        /// <param name="srcBiomes">Ordered biome list that provides blend options and transform context.</param>
        /// <param name="srcDatas">Biome output data parallel to <paramref name="srcBiomes"/>.</param>
        /// <param name="textureBlendContext">Texture blend context containing height-win masks generated by the height pass.</param>
        /// <param name="ctx">Buffer blend context created by <see cref="Begin"/>.</param>
        /// <remarks>
        /// This method blends detail instance buffers, not detail density maps. Detail density maps are texture outputs
        /// and are blended by <see cref="BiomeTextureBlend.BlendDensityMaps"/>.
        /// </remarks>
        internal static void BlendDetailInstanceBuffer(
            BiomeData destData, List<IBiome> srcBiomes, List<BiomeData> srcDatas, BiomeTextureBlend.BlendContext textureBlendContext, BufferBlendContext ctx)
        {
            BlendBufferChannel<DetailTemplate, InstanceSample>(
                destData,
                srcBiomes,
                srcDatas,
                textureBlendContext,
                ctx,
                (data, entries, buffers) => data.GetDetailInstances(entries, buffers),
                (data, entry, buffer) => data.AddDetailInstance(entry, buffer),
                "Detail Instance");

            if (VistaDebugger.isRecording)
            {
                List<DetailTemplate> finalTemplates = new();
                List<ComputeBuffer> finalBuffers = new();
                destData.GetDetailInstances(finalTemplates, finalBuffers);
                for (int i = 0; i < finalBuffers.Count; ++i)
                {
                    string templateName = finalTemplates[i] != null ? finalTemplates[i].name : "Unnamed Template";
                    VistaDebugger.OpenScope($"Detail Instance: {templateName}", DebugScopeType.BlendPass);
                    VistaDebugger.Capture("Final", finalBuffers[i], DebugBufferInterpretation.InstanceSample);
                    VistaDebugger.CloseScope();
                }
            }
        }

        /// <summary>
        /// Blends object instance buffers from all source biomes into <paramref name="destData"/>.
        /// </summary>
        /// <param name="destData">Destination biome data receiving blended object templates and instance buffers.</param>
        /// <param name="srcBiomes">Ordered biome list that provides blend options and transform context.</param>
        /// <param name="srcDatas">Biome output data parallel to <paramref name="srcBiomes"/>.</param>
        /// <param name="textureBlendContext">Texture blend context containing height-win masks generated by the height pass.</param>
        /// <param name="ctx">Buffer blend context created by <see cref="Begin"/>.</param>
        /// <remarks>
        /// Object buffers use the same <see cref="InstanceSample"/> layout as tree and detail-instance buffers, but are
        /// paired with <see cref="ObjectTemplate"/> entries.
        /// </remarks>
        internal static void BlendObjectBuffer(
            BiomeData destData, List<IBiome> srcBiomes, List<BiomeData> srcDatas, BiomeTextureBlend.BlendContext textureBlendContext, BufferBlendContext ctx)
        {
            BlendBufferChannel<ObjectTemplate, InstanceSample>(
                destData,
                srcBiomes,
                srcDatas,
                textureBlendContext,
                ctx,
                (data, entries, buffers) => data.GetObjects(entries, buffers),
                (data, entry, buffer) => data.AddObject(entry, buffer),
                "Object");

            if (VistaDebugger.isRecording)
            {
                List<ObjectTemplate> finalTemplates = new();
                List<ComputeBuffer> finalBuffers = new();
                destData.GetObjects(finalTemplates, finalBuffers);
                for (int i = 0; i < finalBuffers.Count; ++i)
                {
                    string templateName = finalTemplates[i] != null ? finalTemplates[i].name : "Unnamed Template";
                    VistaDebugger.OpenScope($"Object: {templateName}", DebugScopeType.BlendPass);
                    VistaDebugger.Capture("Final", finalBuffers[i], DebugBufferInterpretation.InstanceSample);
                    VistaDebugger.CloseScope();
                }
            }
        }

        /// <summary>
        /// Blends generic position buffers from all source biomes into <paramref name="destData"/>.
        /// </summary>
        /// <param name="destData">Destination biome data receiving blended generic buffer labels and buffers.</param>
        /// <param name="srcBiomes">Ordered biome list that provides blend options and transform context.</param>
        /// <param name="srcDatas">Biome output data parallel to <paramref name="srcBiomes"/>.</param>
        /// <param name="textureBlendContext">Texture blend context containing height-win masks generated by the height pass.</param>
        /// <param name="ctx">Buffer blend context created by <see cref="Begin"/>.</param>
        /// <remarks>
        /// Generic buffers store <see cref="PositionSample"/> values and are identified by string labels rather than
        /// template assets. Labels are preserved as non-distinct entries so custom consumers can decide how to merge or
        /// interpret repeated labels.
        /// </remarks>
        internal static void BlendGenericBuffer(
            BiomeData destData, List<IBiome> srcBiomes, List<BiomeData> srcDatas, BiomeTextureBlend.BlendContext textureBlendContext, BufferBlendContext ctx)
        {
            BlendBufferChannel<string, PositionSample>(
                destData,
                srcBiomes,
                srcDatas,
                textureBlendContext,
                ctx,
                (data, entries, buffers) => data.GetGenericBuffers(entries, buffers),
                (data, entry, buffer) => data.AddGenericBuffer(entry, buffer),
                "Generic Buffer");

            if (VistaDebugger.isRecording)
            {
                List<string> finalLabels = new();
                List<ComputeBuffer> finalBuffers = new();
                destData.GetGenericBuffers(finalLabels, finalBuffers);
                for (int i = 0; i < finalBuffers.Count; ++i)
                {
                    string labelDisplay = string.IsNullOrEmpty(finalLabels[i]) ? "Generic buffer" : $"{finalLabels[i]} (Generic)";
                    VistaDebugger.OpenScope(labelDisplay, DebugScopeType.BlendPass);
                    VistaDebugger.Capture("Final", finalBuffers[i], DebugBufferInterpretation.PositionSample);
                    VistaDebugger.CloseScope();
                }
            }
        }

        /// <summary>
        /// Blends one compute-buffer channel using biome population blend modes.
        /// </summary>
        /// <typeparam name="TEntry">
        /// Channel entry type paired with each buffer. Tree, detail, and object channels use template assets; generic
        /// buffers use string labels.
        /// </typeparam>
        /// <typeparam name="TSample">
        /// Packed sample layout stored in each buffer. Supported values are <see cref="InstanceSample"/> and
        /// <see cref="PositionSample"/>.
        /// </typeparam>
        /// <param name="destData">Destination biome data receiving cloned and masked buffers.</param>
        /// <param name="srcBiomes">Ordered biome list that provides population blend options.</param>
        /// <param name="srcDatas">Biome data outputs parallel to <paramref name="srcBiomes"/>.</param>
        /// <param name="textureBlendContext">Texture blend context used to query height-win masks.</param>
        /// <param name="ctx">Buffer blend context used for mask dispatches.</param>
        /// <param name="getSourceEntries">Callback that reads channel entries and source buffers from a biome data object.</param>
        /// <param name="addDestEntry">Callback that writes one blended channel entry and cloned buffer into <paramref name="destData"/>.</param>
        /// <param name="logStageName">User-facing channel name used in configuration warnings.</param>
        /// <remarks>
        /// The algorithm runs in two phases. First, it walks biomes in stack order and resolves final coverage masks for
        /// every source buffer without touching the source buffers. Replace and Height Win erode masks accumulated from
        /// lower biomes, while Coexist appends without eroding. Second, it clones each source buffer and applies its
        /// resolved coverage mask in-place.
        /// </remarks>
        /// <remarks>
        /// The helper owns all temporary coverage masks it creates and releases them before returning, even when an
        /// exception is thrown after allocation. The cloned compute buffers added to <paramref name="destData"/> are owned
        /// by that destination data object.
        /// </remarks>
        private static void BlendBufferChannel<TEntry, TSample>(
            BiomeData destData,
            List<IBiome> srcBiomes,
            List<BiomeData> srcDatas,
            BiomeTextureBlend.BlendContext textureBlendContext,
            BufferBlendContext ctx,
            System.Action<BiomeData, List<TEntry>, List<ComputeBuffer>> getSourceEntries,
            System.Action<BiomeData, TEntry, ComputeBuffer> addDestEntry,
            string logStageName)
        {
            // These lists are parallel. Each entry represents one output buffer that will be created in phase 2.
            // TEntry is the channel identifier: TreeTemplate, DetailTemplate, ObjectTemplate, or generic label.
            // srcBufferRefs keeps the original source buffer; destCoverageMasks stores the final mask after all upper biomes are applied.
            List<TEntry> destEntries = new();
            List<RenderTexture> destCoverageMasks = new();
            List<ComputeBuffer> srcBufferRefs = new();

            try
            {
                // Phase 1 resolves ownership as textures only; source buffers are not cloned or modified here.
                for (int iBiome = 0; iBiome < srcDatas.Count; ++iBiome)
                {
                    IBiome biome = srcBiomes[iBiome];
                    BiomeData srcData = srcDatas[iBiome];
                    RenderTexture biomeMask = srcData.biomeMaskMap;
                    if (biomeMask == null)
                    {
                        // No mask means no coverage for this biome in this channel.
                        continue;
                    }

                    BiomeBlendOptions.PopulationBlendMode blendMode = biome.blendOptions.populationBlendMode;
                    List<TEntry> srcEntries = new();
                    List<ComputeBuffer> srcBuffers = new();
                    getSourceEntries(srcData, srcEntries, srcBuffers);

                    if (blendMode == BiomeBlendOptions.PopulationBlendMode.Replace)
                    {
                        // Replace claims its mask region by eroding all lower entries first.
                        for (int iDestMask = 0; iDestMask < destCoverageMasks.Count; ++iDestMask)
                        {
                            BiomeTextureBlend.ErodeCoverageMask(textureBlendContext, destCoverageMasks[iDestMask], biomeMask);
                        }

                        // Then append this biome's buffers with the original biome mask as coverage.
                        for (int iBuffer = 0; iBuffer < srcBuffers.Count; ++iBuffer)
                        {
                            RenderTexture destCoverageMask = GraphicsUtils.CloneToRenderTexture(biomeMask);
                            destEntries.Add(srcEntries[iBuffer]);
                            srcBufferRefs.Add(srcBuffers[iBuffer]);
                            destCoverageMasks.Add(destCoverageMask);
                        }
                    }
                    else if (blendMode == BiomeBlendOptions.PopulationBlendMode.Coexist)
                    {
                        // Coexist appends this biome's buffers without modifying lower entries.
                        for (int iBuffer = 0; iBuffer < srcBuffers.Count; ++iBuffer)
                        {
                            RenderTexture destCoverageMask = GraphicsUtils.CloneToRenderTexture(biomeMask);
                            destEntries.Add(srcEntries[iBuffer]);
                            srcBufferRefs.Add(srcBuffers[iBuffer]);
                            destCoverageMasks.Add(destCoverageMask);
                        }
                    }
                    else if (blendMode == BiomeBlendOptions.PopulationBlendMode.HeightWin)
                    {
                        RenderTexture heightWinMask = textureBlendContext.GetHeightWinMask(iBiome);
                        if (heightWinMask == null)
                        {
                            // Height Win depends on the height blend pass; without height output, this biome wins nowhere.
                            Debug.Log(
                                $"[Biome Blend/{logStageName}] Biome '{biome.gameObject.name}' uses Height Win population blending, but it has no height output. Enable Height in the Data Mask and add a Height Output node.");
                            continue;
                        }

                        RenderTexture filteredBiomeMask = GraphicsUtils.GetBlankTempRT(biomeMask.width, biomeMask.format);
                        try
                        {
                            // The filtered mask is the biome mask limited to pixels where this biome won the height pass.
                            BiomeTextureBlend.FilterBiomeMaskWithHeightWinMask(
                                textureBlendContext, biomeMask, heightWinMask, filteredBiomeMask);

                            // Height Win claims only the filtered region, leaving lower entries outside winning pixels.
                            for (int iDestMask = 0; iDestMask < destCoverageMasks.Count; ++iDestMask)
                            {
                                BiomeTextureBlend.ErodeCoverageMask(textureBlendContext, destCoverageMasks[iDestMask], filteredBiomeMask);
                            }

                            // Append this biome's buffers with the filtered mask as coverage.
                            for (int iBuffer = 0; iBuffer < srcBuffers.Count; ++iBuffer)
                            {
                                RenderTexture destCoverageMask = GraphicsUtils.CloneToRenderTexture(filteredBiomeMask);
                                destEntries.Add(srcEntries[iBuffer]);
                                srcBufferRefs.Add(srcBuffers[iBuffer]);
                                destCoverageMasks.Add(destCoverageMask);
                            }
                        }
                        finally
                        {
                            GraphicsUtils.ReleaseTempRT(filteredBiomeMask);
                        }
                    }
                    else
                    {
                        throw new System.NotImplementedException(
                            $"No {logStageName} buffer implementation for PopulationBlendMode.{blendMode}. Add a case here.");
                    }
                }

                // Phase 2 clones each source buffer and applies its resolved coverage mask.
                for (int iEntry = 0; iEntry < srcBufferRefs.Count; ++iEntry)
                {
                    ComputeBuffer clonedBuffer = BufferHelper.Clone(srcBufferRefs[iEntry]);
                    DispatchBufferMask<TSample>(ctx, clonedBuffer, destCoverageMasks[iEntry], flipMask: false);
                    addDestEntry(destData, destEntries[iEntry], clonedBuffer);
                }
            }
            finally
            {
                // Coverage masks are temporary working textures owned by this helper.
                ReleaseCoverageMasks(destCoverageMasks);
            }
        }

        /// <summary>
        /// Releases temporary coverage masks allocated while blending a buffer channel.
        /// </summary>
        /// <param name="coverageMasks">Render textures owned by the current blend operation.</param>
        /// <remarks>
        /// Unity warns when releasing a render texture that is still active. The method clears
        /// <see cref="RenderTexture.active"/> only when it points to the texture being released.
        /// </remarks>
        private static void ReleaseCoverageMasks(List<RenderTexture> coverageMasks)
        {
            for (int iMask = 0; iMask < coverageMasks.Count; ++iMask)
            {
                if (RenderTexture.active == coverageMasks[iMask])
                {
                    RenderTexture.active = null;
                }
                coverageMasks[iMask].Release();
                Object.DestroyImmediate(coverageMasks[iMask]);
            }
        }

        /// <summary>
        /// Applies a coverage mask to a packed sample buffer in-place.
        /// </summary>
        /// <typeparam name="T">
        /// Packed sample layout stored in <paramref name="buffer"/>. Supported values are <see cref="InstanceSample"/>
        /// and <see cref="PositionSample"/>.
        /// </typeparam>
        /// <param name="ctx">Buffer blend context used for shader dispatch.</param>
        /// <param name="buffer">Compute buffer containing packed sample data. The buffer is modified in-place.</param>
        /// <param name="biomeMask">Coverage mask sampled in normalized XZ sample space. A null mask is treated as black.</param>
        /// <param name="flipMask">
        /// When false, samples outside the mask are invalidated. When true, samples inside the mask are invalidated.
        /// </param>
        /// <remarks>
        /// The shader uses stochastic culling based on sample position so partially covered biome edges preserve a stable
        /// scattered look instead of creating hard rectangular truncation. Large buffers are processed in batches to stay
        /// within the per-dispatch thread-group limit.
        /// </remarks>
        /// <exception cref="System.ArgumentException">
        /// Thrown when <typeparamref name="T"/> is not a supported sample type, or when the buffer length is not an exact
        /// multiple of that sample type's packed float count.
        /// </exception>
        private static void DispatchBufferMask<T>(
            BufferBlendContext ctx, ComputeBuffer buffer, Texture biomeMask, bool flipMask)
        {
            int sampleSize;
            string sampleTypeKeyword;
            if (typeof(T).Equals(typeof(InstanceSample)))
            {
                sampleSize = InstanceSample.SIZE;
                sampleTypeKeyword = KW_DATA_TYPE_INSTANCE_SAMPLE;
            }
            else if (typeof(T).Equals(typeof(PositionSample)))
            {
                sampleSize = PositionSample.SIZE;
                sampleTypeKeyword = KW_DATA_TYPE_POSITION_SAMPLE;
            }
            else
            {
                throw new System.ArgumentException($"Buffer data type must be {typeof(InstanceSample).Name} or {typeof(PositionSample).Name}");
            }

            if (buffer.count % sampleSize != 0)
            {
                throw new System.ArgumentException("Buffer size and sample size do not match.");
            }

            ctx.shader.SetBuffer(ctx.kernel, SRC_BUFFER, buffer);
            ctx.shader.SetTexture(ctx.kernel, MASK_MAP, biomeMask != null ? biomeMask : Texture2D.blackTexture);
            // Clear all keywords before setting per-dispatch ones to avoid state leaking between calls.
            ctx.shader.shaderKeywords = null;
            ctx.shader.EnableKeyword(sampleTypeKeyword);
            if (flipMask)
            {
                ctx.shader.EnableKeyword(KW_FLIP_MASK);
            }

            int sampleCount = buffer.count / sampleSize;
            int totalThreadGroupX = (sampleCount + THREAD_PER_GROUP - 1) / THREAD_PER_GROUP;
            int iteration = (totalThreadGroupX + MAX_THREAD_GROUP - 1) / MAX_THREAD_GROUP;
            for (int i = 0; i < iteration; ++i)
            {
                int threadGroupX = Mathf.Min(MAX_THREAD_GROUP, totalThreadGroupX);
                totalThreadGroupX -= MAX_THREAD_GROUP;
                int baseIndex = i * MAX_THREAD_GROUP * THREAD_PER_GROUP;
                ctx.shader.SetInt(BASE_INDEX, baseIndex);
                ctx.shader.Dispatch(ctx.kernel, threadGroupX, 1, 1);
            }
        }
    }
}
#endif
