#if VISTA
using UnityEngine;

namespace Pinwheel.Vista
{
    [CreateAssetMenu(menuName = "Vista/Object Template")]
    [HelpURL("https://docs.pinwheelstud.io/vista/docs/object-template.html")]
    /// <summary>
    /// Describes how Vista should spawn object instances generated by an object output node.
    /// </summary>
    /// <remarks>
    /// Object templates are paired with <see cref="InstanceSample"/> buffers in <see cref="BiomeData"/> and consumed by
    /// terrain-system object populators. Each valid sample chooses one prefab from the primary prefab plus any supported
    /// variants, then applies sampled rotation and scale before optional alignment to the terrain normal.
    /// </remarks>
    public class ObjectTemplate : ScriptableObject
    {
        [SerializeField]
        private GameObject m_prefab;
        /// <summary>
        /// Gets or sets the primary prefab spawned for this object template.
        /// </summary>
        /// <remarks>
        /// This prefab is required for the template to be valid. When no variant is available or selected, each generated
        /// instance uses this object as the spawn source.
        /// </remarks>
        public GameObject prefab
        {
            get
            {
                return m_prefab;
            }
            set
            {
                m_prefab = value;
            }
        }

        [SerializeField]
        protected GameObject[] m_prefabVariants;
        /// <summary>
        /// Gets or sets additional prefab variants that may be selected when spawning instances.
        /// </summary>
        /// <remarks>
        /// The getter returns a copy of the stored array and returns an empty array when variant support is unavailable in
        /// the current integration. Null assignments are converted to an empty array. During population, non-null variants
        /// are appended to the candidate prefab list and one candidate is chosen randomly for each valid sample.
        /// </remarks>
        public GameObject[] prefabVariants
        {
            get
            {
                if (!TemplateUtils.IsVariantsSupported())
                {
                    return new GameObject[0];
                }

                if (m_prefabVariants == null)
                {
                    return new GameObject[0];
                }
                else
                {
                    GameObject[] variants = new GameObject[m_prefabVariants.Length];
                    m_prefabVariants.CopyTo(variants, 0);
                    return variants;
                }
            }
            set
            {
                if (value == null)
                {
                    m_prefabVariants = new GameObject[0];
                }
                else
                {
                    m_prefabVariants = new GameObject[value.Length];
                    value.CopyTo(m_prefabVariants, 0);
                }
            }
        }

        [SerializeField]
        private bool m_alignToNormal;
        /// <summary>
        /// Gets or sets whether spawned instances should be rotated toward the terrain normal.
        /// </summary>
        /// <remarks>
        /// When enabled, object populators compute a terrain normal at the sample position, blend it with
        /// <see cref="Vector3.up"/> using <see cref="normalAlignmentError"/>, then apply the resulting alignment on top of
        /// the sampled Y rotation from the instance buffer.
        /// </remarks>
        public bool alignToNormal
        {
            get
            {
                return m_alignToNormal;
            }
            set
            {
                m_alignToNormal = value;
            }
        }

        [SerializeField]
        private float m_normalAlignmentError;
        /// <summary>
        /// Gets or sets how much random deviation is allowed when aligning spawned objects to the terrain normal.
        /// </summary>
        /// <remarks>
        /// The value is clamped to <c>[0, 1]</c>. A value of 0 uses the terrain normal exactly, while larger values widen
        /// the random interpolation range around that normal by varying the blend factor between <c>1 - value</c> and
        /// <c>1 + value</c>.
        /// </remarks>
        public float normalAlignmentError
        {
            get
            {
                return m_normalAlignmentError;
            }
            set
            {
                m_normalAlignmentError = Mathf.Clamp01(value);
            }
        }

        /// <summary>
        /// Restores the template to the default object-spawning configuration.
        /// </summary>
        /// <remarks>
        /// The defaults disable terrain-normal alignment and clear the primary prefab reference. Variant data is left
        /// unchanged by this method.
        /// </remarks>
        public void Reset()
        {
            m_prefab = null;
            m_alignToNormal = false;
            m_normalAlignmentError = 0;
        }

        /// <summary>
        /// Tests whether the template has the minimum data required for object population.
        /// </summary>
        /// <returns>
        /// <see langword="true"/> when <see cref="prefab"/> is assigned; otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// Variant prefabs are optional and do not make an otherwise empty template valid.
        /// </remarks>
        public bool IsValid()
        {
            return m_prefab != null;
        }
    }
}
#endif


