#if VISTA

namespace Pinwheel.Vista.Graph
{
    /// <summary>
    /// Selects the fractal noise variant generated by Vista noise shaders and graph noise nodes.
    /// </summary>
    public enum NoiseMode
    {
        /// <summary>
        /// Raw Perlin-style output without remapping it into the normalized 0..1 range.
        /// </summary>
        PerlinRaw,
        /// <summary>
        /// Perlin-style output remapped into the normalized 0..1 range.
        /// </summary>
        Perlin01,
        /// <summary>
        /// Billow noise derived from the absolute value of the base noise to create rounded ridges.
        /// </summary>
        Billow,
        /// <summary>
        /// Ridged noise that inverts peaks and valleys to emphasize sharp mountain-like crests.
        /// </summary>
        Ridged,
        /// <summary>
        /// OpenSimplex noise variant exposed by the shared noise shader path.
        /// </summary>
        OpenSimplex
    }
}
#endif


